version: '3'
services:
  app:
    build: .
    container_name: omnibackend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
