version: '3'
services:
  app:
    build: .
    container_name: omnibackend
    ports:
      - "80:3000"  # Mapeia a porta 80 do host para a porta 3000 do container
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
